[package]
org = "wso2bfsi"
name = "bfsi_payment_initiation_api"
version = "1.0.0"
export = ["bfsi_payment_initiation_api","bfsi_payment_initiation_api.interceptor","bfsi_payment_initiation_api.model","bfsi_payment_initiation_api.util"]
distribution = "2201.3.1"
authors = ["WSO2 BFSI"]
keywords = ["Type/RestApi","Category/Service","Internal/http","Cost/Free","Vertical/bfsi"]
icon = "docs/icon.png"

[build-options]
observabilityIncluded = true
